/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { DecentramallTokenContract } from "./DecentramallToken";
import { EstateAgentContract } from "./EstateAgent";
import { RentalAgentContract } from "./RentalAgent";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DecentramallToken"): DecentramallTokenContract;
      require(name: "EstateAgent"): EstateAgentContract;
      require(name: "RentalAgent"): RentalAgentContract;
    }
  }
}

export {
  DecentramallTokenContract,
  DecentramallTokenInstance
} from "./DecentramallToken";
export { EstateAgentContract, EstateAgentInstance } from "./EstateAgent";
export { RentalAgentContract, RentalAgentInstance } from "./RentalAgent";
